### ISSUE TITLE
Um Ansible Playbook "TL;DR" de um nó tudo-em-um do Tsuru PaaS

### ISSUE THREAD

**Issue by fititnt** [EticaAI/aguia-pescadora#27]
Tão logo seja possível algo próximo do #26 (ou talvez antes dele) podemos tentar uma opção que assume que um profissional já sabe o que está fazendo e só quer saber o que colar para ter resultado imediato.

Esse TL;DR; pode assumir coisas como o alvo ser um sistema operacional específico e já ter uma conta SSH previamente criada e pronta para fazer o que deveria.

Repositório de referência: https://github.com/EticaAI/aguia-pescadora-ansible-playbooks

**Comment by fititnt** [comment]
Hummm... é possível.

tldr.yml
```yaml
- name: tldr tsuru client? docker? docker-machine?
  hosts: localhost
  tasks:
    - name: tsuru client? https://tsuru-client.readthedocs.io/en/latest/installing.html
      shell: tsuru --version
      register: result
      ignore_errors: false

    - name: docker? https://docs.docker.com/install/
      shell: docker --version
      register: result2
      ignore_errors: false

    - name: docker-machine? https://docs.docker.com/machine/install-machine/
      shell: docker-machine version
      register: result3
      ignore_errors: false
```


```bash
# fititnt at bravo in /alligo/code/eticaai/aguia-pescadora-ansible-playbooks on git:master x [4:34:49]
$ ansible-playbook tldr.yml -e tsuru_host=aguia-pescadora-delta.etica.ai

PLAY [tldr tsuru client? docker? docker-machine?] ******************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [tsuru client? https://tsuru-client.readthedocs.io/en/latest/installing.html] ***
changed: [localhost]

TASK [docker? https://docs.docker.com/install/] ********************************
changed: [localhost]

TASK [docker-machine? https://docs.docker.com/machine/install-machine/] ********
changed: [localhost]

PLAY [tldr] ********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [modo para forçar servidor de destino como target] ************************
ok: [localhost]

PLAY [tldr, target] ************************************************************

TASK [teste se fucionou] *******************************************************
ok: [aguia-pescadora-delta.etica.ai] => {
    "msg": "I'm on aguia-pescadora-delta.etica.ai"
}

PLAY RECAP *********************************************************************
aguia-pescadora-delta.etica.ai : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
localhost                  : ok=6    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


# fititnt at bravo in /alligo/code/eticaai/aguia-pescadora-ansible-playbooks on git:master x [4:34:56]
$ 
```
