### ISSUE TITLE
Instalação básica de Minio em clusters pequenos (inclusive os de um nó tudo-em-um)

### ISSUE THREAD

**Issue by fititnt** [EticaAI/aguia-pescadora#28]
Aplicável a #26 #27 #22 

---
Ponto de questão sobre instalação básica de Minio em clusters pequenos (inclusive os de um nó tudo-em-um).

Uma possível aplicação seria
- https://snapcraft.io/install/minio/ubuntu
- https://docs.ansible.com/ansible/latest/modules/snap_module.html

**Comment by fititnt** [comment]
```yaml
# minio-install.yml

# TODO: este comando pode pedir para reiniciar a maquina para poder ser detectado no path. Resolver isto (fititnt, 2019-07-01 14:39 BRT)
- name: "snapd: sudo apt install snapd"
  apt:
    name: snapd

- name: sudo snap install minio --edge
  snap:
    name: minio
    channel: edge
```


```bash
root@aguia-pescadora-foxtrot:~# minio
minio: relocation error: /snap/minio/1186/lib/x86_64-linux-gnu/libpthread.so.0: symbol __mmap, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

Mesmo erro que acontece em 

- https://github.com/minio/minio/issues/6933
- https://github.com/minio/minio/issues/5472
- https://forum.snapcraft.io/t/glibc-private-not-defined-in-file-libc-so-6-with-link-time-reference/3631

---
Edit: adicionado comandos o Ansible usados.
