### ISSUE TITLE
aguia-pescadora-ansible-playbooks/tarefa/firewal falha no primeiro teste ("Ubuntu? Debian?") em função de `gather_facts: no`

### ISSUE THREAD

**Issue by fititnt** [EticaAI/aguia-pescadora#35]
Reportado por @cdiegosr 

---

A tarefa aguia-pescadora-ansible-playbooks/tarefa/firewall disponibilizada em https://github.com/EticaAI/aguia-pescadora-ansible-playbooks/tree/master/tarefa/firewall (e cujo arquivo exato antes de correção pode ser vista em https://github.com/EticaAI/aguia-pescadora-ansible-playbooks/blob/22d8d19ce7271377f2fd22cb5e1be43f1744ce7f/tarefa/firewall/firewall.yml) pode dar um falso positivo no primeiro teste quando testado em certas situações. Mesmo o host de destino sendo um Ubuntu, ele falha.

```yaml
- hosts: all
  gather_facts: no
  tasks:

  - name: Ubuntu? Debian?
    fail:
      msg: "Ubuntu/Debian fail"
    when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

# ...
```

Uma das formas que resolve imediatamente sem precisar documentar poderia ser não forçar o `gather_facts: no`.
